name: 10-running-C
on:
  push:
    branches: [main]
    paths: "*.c"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile C code
        run: gcc -o myprogram *.c
      - name: Run the program
        run: ./myprogram > sample.txt
      - name: Show the output
        run: cat sample.txt
      - name: Commit it back
        run: |
          git config --global user.name "SideztChasm08"
          git config --global user.email "sideztchasm08@gmail.com"
          git add sample.txt
          git diff --staged --quiet || git commit -m "Update sample output"
          git push
